services:
  mc:
    container_name: duneraft-mc
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    user: "${USER_UID-0}:${USER_GID-0}"
    environment:
      UID: "${MC_UID}"
      GID: "${MC_GID}"
      VERSION: "1.21.10"
      EULA: "true"
      TYPE: "FABRIC"
      MEMORY: "16G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      RCON_PORT: "${RCON_PORT}"
      JVM_OPTS: -Dminecraft.api.env=custom -Dminecraft.api.auth.host=https://dualie.ink/drasl/auth -Dminecraft.api.account.host=https://dualie.ink/drasl/account -Dminecraft.api.session.host=https://dualie.ink/drasl/session -Dminecraft.api.services.host=https://dualie.ink/drasl/services
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_PROJECTS: |
        fabric-api
        lithium
        your-items-are-safe
        ledger
        simple-voice-chat:beta
        servux
        distanthorizons:beta
    volumes:
      - ./data:/data
      - ./mods:/mods
    tty: true
    restart: unless-stopped
  mc-backup-sidecar:
    user: "${USER_UID-0}:${USER_GID-0}"
    container_name: duneraft-mc-backup-sidecar
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "24h"
      EXCLUDES: "world/ledger.sqlite,world/data/DistantHorizons.sqlite,world/DIM-1/data/DistantHorizons.sqlite,world/DIM1/data/DistantHorizons.sqlite"
      PRUNE_BACKUPS_DAYS: "-1"  # -1 means no pruning
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
      # As an example, to backup only the world data:
      # INCLUDES: world,world_nether,world_the_end
    volumes:
      - ./data:/data:ro
      - ${BACKUP_HOST_PATH}:/backups
  mc-restore-sidecar:
    user: "${USER_UID-0}:${USER_GID-0}"
    container_name: duneraft-mc-restore-sidecar
    # Same image as mc, but any base image with bash and tar will work
    image: itzg/mc-backup
    restart: "no"
    entrypoint: restore-tar-backup
    volumes:
      # Must be same mount as mc service, needs to be writable
      - ./data:/data
      # Must be same mount as backups service, but can be read-only
      - ${BACKUP_HOST_PATH}:/backups:ro
  rcon:
    container_name: duneraft-rcon
    image: itzg/rcon-cli
    depends_on:
      mc:
        condition: service_healthy
    tty: true
    entrypoint: ["/rcon-cli", "--host", "mc", "--port", "${RCON_PORT}", "--password", "${RCON_PASSWORD}"]
    restart: no
  mokago:
    container_name: mokago
    depends_on:
      mc:
        condition: service_healthy
    image: golang
    volumes:
      - ./mokago:/mokago
      - ./data:/data
    working_dir: /mokago
    environment:
      RCON_ADDR: "mc:${RCON_PORT}"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      MOKAGO_TOKEN: "${MOKAGO_TOKEN}"
      MOKAGO_WHITELIST_ROLE_ID: "${MOKAGO_WHITELIST_ROLE_ID}"
      MOKAGO_SUS_ROLE_ID: "${MOKAGO_SUS_ROLE_ID}"
      MOKAGO_GUILD_ID: "${MOKAGO_GUILD_ID}"
      MOKAGO_APPLICATION_ID: "${MOKAGO_APPLICATION_ID}"
      DATA_DIR: "/data"
    command: |
      go run main.go
    restart: unless-stopped
